---
generator_definitions:
  - name: tag_duplicator
    file_path: "duplicator.py"
    targets: tags
    query: tag_query
    class_name: TagDuplicator
    parameters:
      name: "name__value"

queries:
  - name: tag_query
    file_path: ./tag.gql
